# https://packaging.python.org/en/latest/guides/writing-pyproject-toml
# [project]
# requires-python = ">=3.10"

# https://microsoft.github.io/pyright/#/configuration
[tool.pyright]
# Paths of directories or files that should be considered part of the project.
include = ["src"]
# Paths of directories or files that should not be considered part of the project.
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "src/experimental",
]

# root: Root path for the code that will execute within this execution environment.
# extraPaths: Additional search paths that will be used when searching for modules imported by files.
executionEnvironments = [
  { root = "src/tests", extraPaths = ["src/tests/e2e", "src/sdk"] },
  { root = "src" }
]

# output logs should be verbose.
verboseOutput = true

# python3 -m venv .venv
venvPath = "."
venv = ".venv"

# https://docs.astral.sh/ruff/tutorial/#configuration
[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
extend-select = ["E501"]
